-work common_cells
-sv
-d XSIM
-d VERILATOR

-i ${COMMON_CELLS}/include

${COMMON_CELLS}/src/cb_filter_pkg.sv
${COMMON_CELLS}/src/cf_math_pkg.sv
${COMMON_CELLS}/src/ecc_pkg.sv
${COMMON_CELLS}/src/cdc_reset_ctrlr_pkg.sv

${COMMON_CELLS}/src/binary_to_gray.sv
${COMMON_CELLS}/src/cc_onehot.sv
${COMMON_CELLS}/src/clk_int_div.sv
${COMMON_CELLS}/src/credit_counter.sv
${COMMON_CELLS}/src/delta_counter.sv
${COMMON_CELLS}/src/edge_propagator_tx.sv
${COMMON_CELLS}/src/exp_backoff.sv
${COMMON_CELLS}/src/fifo_v3.sv
${COMMON_CELLS}/src/gray_to_binary.sv
${COMMON_CELLS}/src/heaviside.sv
${COMMON_CELLS}/src/isochronous_4phase_handshake.sv
${COMMON_CELLS}/src/isochronous_spill_register.sv
${COMMON_CELLS}/src/lfsr.sv
${COMMON_CELLS}/src/lfsr_16bit.sv
${COMMON_CELLS}/src/lfsr_8bit.sv
${COMMON_CELLS}/src/multiaddr_decode.sv
${COMMON_CELLS}/src/mv_filter.sv
${COMMON_CELLS}/src/onehot_to_bin.sv
${COMMON_CELLS}/src/plru_tree.sv
${COMMON_CELLS}/src/passthrough_stream_fifo.sv
${COMMON_CELLS}/src/popcount.sv
${COMMON_CELLS}/src/ring_buffer.sv
${COMMON_CELLS}/src/rr_arb_tree.sv
${COMMON_CELLS}/src/rstgen_bypass.sv
${COMMON_CELLS}/src/serial_deglitch.sv
${COMMON_CELLS}/src/shift_reg.sv
${COMMON_CELLS}/src/shift_reg_gated.sv
${COMMON_CELLS}/src/spill_register_flushable.sv
${COMMON_CELLS}/src/stream_demux.sv
${COMMON_CELLS}/src/stream_filter.sv
${COMMON_CELLS}/src/stream_fork.sv
${COMMON_CELLS}/src/stream_intf.sv
${COMMON_CELLS}/src/stream_join.sv
${COMMON_CELLS}/src/stream_join_dynamic.sv
${COMMON_CELLS}/src/stream_mux.sv
${COMMON_CELLS}/src/stream_throttle.sv
${COMMON_CELLS}/src/sub_per_hash.sv
${COMMON_CELLS}/src/sync.sv
${COMMON_CELLS}/src/sync_wedge.sv
${COMMON_CELLS}/src/unread.sv
${COMMON_CELLS}/src/read.sv
${COMMON_CELLS}/src/addr_decode_dync.sv
${COMMON_CELLS}/src/boxcar.sv
${COMMON_CELLS}/src/cdc_2phase.sv
${COMMON_CELLS}/src/cdc_4phase.sv
${COMMON_CELLS}/src/cb_filter.sv
${COMMON_CELLS}/src/cdc_fifo_2phase.sv
${COMMON_CELLS}/src/counter.sv
${COMMON_CELLS}/src/ecc_decode.sv
${COMMON_CELLS}/src/ecc_encode.sv
${COMMON_CELLS}/src/edge_detect.sv
${COMMON_CELLS}/src/lzc.sv
${COMMON_CELLS}/src/max_counter.sv
${COMMON_CELLS}/src/rstgen.sv
${COMMON_CELLS}/src/spill_register.sv
${COMMON_CELLS}/src/stream_delay.sv
${COMMON_CELLS}/src/stream_fifo.sv
${COMMON_CELLS}/src/stream_fork_dynamic.sv
${COMMON_CELLS}/src/trip_counter.sv
${COMMON_CELLS}/src/clk_mux_glitch_free.sv
${COMMON_CELLS}/src/addr_decode.sv
${COMMON_CELLS}/src/addr_decode_napot.sv
${COMMON_CELLS}/src/cdc_reset_ctrlr.sv
${COMMON_CELLS}/src/cdc_fifo_gray.sv
${COMMON_CELLS}/src/fall_through_register.sv
${COMMON_CELLS}/src/id_queue.sv
${COMMON_CELLS}/src/stream_to_mem.sv
${COMMON_CELLS}/src/stream_arbiter_flushable.sv
${COMMON_CELLS}/src/stream_fifo_optimal_wrap.sv
${COMMON_CELLS}/src/stream_register.sv
${COMMON_CELLS}/src/stream_xbar.sv
${COMMON_CELLS}/src/cdc_fifo_gray_clearable.sv
${COMMON_CELLS}/src/cdc_2phase_clearable.sv
${COMMON_CELLS}/src/mem_to_banks_detailed.sv
${COMMON_CELLS}/src/stream_arbiter.sv
${COMMON_CELLS}/src/stream_omega_net.sv
${COMMON_CELLS}/src/mem_to_banks.sv
${COMMON_CELLS}/src/deprecated/clock_divider.sv
${COMMON_CELLS}/src/deprecated/clock_divider_counter.sv
${COMMON_CELLS}/src/deprecated/find_first_one.sv
${COMMON_CELLS}/src/deprecated/generic_LFSR_8bit.sv
${COMMON_CELLS}/src/deprecated/generic_fifo.sv
${COMMON_CELLS}/src/deprecated/generic_fifo_adv.sv
${COMMON_CELLS}/src/deprecated/pulp_sync.sv
${COMMON_CELLS}/src/deprecated/pulp_sync_wedge.sv
${COMMON_CELLS}/src/deprecated/sram.sv
${COMMON_CELLS}/src/deprecated/fifo_v2.sv
${COMMON_CELLS}/src/deprecated/prioarbiter.sv
${COMMON_CELLS}/src/deprecated/rrarbiter.sv
${COMMON_CELLS}/src/deprecated/fifo_v1.sv
${COMMON_CELLS}/src/edge_propagator_ack.sv
${COMMON_CELLS}/src/edge_propagator.sv
${COMMON_CELLS}/src/edge_propagator_rx.sv
